# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
ruby '3.0.0'
# gem "rails"

gem "pg", "~> 1.4"

gem "rspec", "~> 3.11"

gem "rack-test", "~> 2.0"

gem "sinatra", "~> 2.2"

gem "webrick", "~> 1.7"
